spacing = 2
padding = 0
hide_ascii = false
hide_bar_delimiters = false
prefer_small_ascii = false
separator = ">"
key_color = "Red"
separator_color = "White"
palette = "Light"

[bar]
glyph = "o"
symbol_open = '['
symbol_close = ']'
visible = true

[box]
title = "[ ArchBox ]"
visible = true

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
color = "Red"
path = "~/macchina/src/macchina-5.0.2/ascii/archlinux.ascii"

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"
